# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78a42b2a759239cfad570208c9a3f79d16e5517bf84e642a04a7b3490746430710f1ff451f0e56002b2c83ddb91eed3eaf6851e28d60ff06a6ef426464dac743

test:
  secret_key_base: d77938269d79d3e66e8d4f8512400cc7ba2506697c8a9fc0855d982e7f0c2261390d2159ccccf9b718f2263d3d31d20247f5e685b419ab71c32e331b3ad6eab7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
